[smtown_news]
title = "SMTOWN ─ Girls' Generation"
url = "https://www.smtown.com/search?type=sub_news&keyword=%EC%86%8C%EB%85%80%EC%8B%9C%EB%8C%80"
entrySelector = "ul.search_news.artist li"
titleSelector = "span.title"
linkSelector = "a.btn_text"
imageSelector = "a[class='btn_img bg_cover']"
contentSelector = "span.text"
waitUntil = "networkidle"
